// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns health check status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Information about health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/flatty-budget_go-api_http_dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/resident-location": {
            "get": {
                "description": "Returns all resident location from the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resident_location"
                ],
                "summary": "List all resident location",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of products to return (default 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of products to skip (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/flatty-budget_go-api_http_dto.ListResidentLocationResponse"
                        }
                    }
                }
            }
        },
        "/resident-location/count": {
            "get": {
                "description": "Returns count resident location from the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resident_location"
                ],
                "summary": "Count all resident location",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/flatty-budget_go-api_http_dto.CountResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "flatty-budget_go-api_http_dto.CountResponse": {
            "type": "object",
            "required": [
                "total"
            ],
            "properties": {
                "total": {
                    "type": "integer",
                    "example": 138
                }
            }
        },
        "flatty-budget_go-api_http_dto.HealthResponse": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "flatty-budget_go-api_http_dto.ListResidentLocationResponse": {
            "type": "object",
            "required": [
                "data",
                "total"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/flatty-budget_go-api_http_dto.ResidentLocationResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "flatty-budget_go-api_http_dto.ResidentLocationResponse": {
            "type": "object",
            "required": [
                "apartment",
                "city",
                "country",
                "created_at",
                "house",
                "id",
                "postal_code",
                "street",
                "updated_at"
            ],
            "properties": {
                "apartment": {
                    "type": "string",
                    "example": "2"
                },
                "city": {
                    "type": "string",
                    "example": "Warsaw"
                },
                "country": {
                    "type": "string",
                    "example": "Poland"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-07-09 08:34:05.796617"
                },
                "house": {
                    "type": "string",
                    "example": "1"
                },
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "postal_code": {
                    "type": "string",
                    "example": "00-945"
                },
                "street": {
                    "type": "string",
                    "example": "Bobr"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-07-09 08:34:05.796617"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "GO API",
	Description:      "TBD",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
