basePath: /api
definitions:
  flatty-budget_go-api_http_dto.CountResponse:
    properties:
      total:
        example: 138
        type: integer
    required:
    - total
    type: object
  flatty-budget_go-api_http_dto.HealthResponse:
    properties:
      status:
        example: ok
        type: string
    required:
    - status
    type: object
info:
  contact: {}
  description: TBD
  title: GO API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns health check status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/flatty-budget_go-api_http_dto.HealthResponse'
      summary: Information about health status
      tags:
      - health
  /resident-location/count:
    get:
      description: Returns count resident location from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/flatty-budget_go-api_http_dto.CountResponse'
      summary: Count all resident location
      tags:
      - resident_location
swagger: "2.0"
