basePath: /api
definitions:
  dto.CountResponse:
    properties:
      total:
        example: 138
        type: integer
    required:
    - total
    type: object
  dto.CreateResidentLocationRequest:
    properties:
      apartment:
        example: "2"
        type: string
      city:
        example: Warsaw
        type: string
      country:
        example: Poland
        type: string
      house:
        example: "1"
        type: string
      postal_code:
        example: 00-945
        type: string
      street:
        example: Bobr
        type: string
    required:
    - apartment
    - city
    - country
    - house
    - postal_code
    - street
    type: object
  dto.DeleteResidentLocationResponse:
    properties:
      data:
        example: 1
        type: integer
    required:
    - data
    type: object
  dto.HealthResponse:
    properties:
      status:
        example: ok
        type: string
    required:
    - status
    type: object
  dto.ListResidentLocationResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.ResidentLocationResponse'
        type: array
      total:
        type: integer
    required:
    - data
    - total
    type: object
  dto.ResidentLocationResponse:
    properties:
      apartment:
        example: "2"
        type: string
      city:
        example: Warsaw
        type: string
      country:
        example: Poland
        type: string
      created_at:
        example: "2026-07-09 08:34:05.796617"
        type: string
      house:
        example: "1"
        type: string
      id:
        example: 123
        type: integer
      postal_code:
        example: 00-945
        type: string
      street:
        example: Bobr
        type: string
      updated_at:
        example: "2026-07-09 08:34:05.796617"
        type: string
    required:
    - apartment
    - city
    - country
    - created_at
    - house
    - id
    - postal_code
    - street
    - updated_at
    type: object
  dto.UpdateResidentLocationRequest:
    properties:
      apartment:
        example: "2"
        type: string
      city:
        example: Warsaw
        type: string
      country:
        example: Poland
        type: string
      house:
        example: "1"
        type: string
      postal_code:
        example: 00-945
        type: string
      street:
        example: Bobr
        type: string
    required:
    - apartment
    - city
    - country
    - house
    - postal_code
    - street
    type: object
info:
  contact: {}
  description: TBD
  title: GO API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns health check status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HealthResponse'
      summary: Information about health status
      tags:
      - health
  /resident-location:
    get:
      description: Returns all resident location from the database
      parameters:
      - description: Number of products to return (default 10)
        in: query
        name: limit
        type: integer
      - description: Number of products to skip (default 0)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ListResidentLocationResponse'
      summary: List all resident location
      tags:
      - resident_location
    post:
      consumes:
      - application/json
      description: Add a new resident location to the database
      parameters:
      - description: Resident Location data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateResidentLocationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ResidentLocationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a resident location
      tags:
      - resident_location
  /resident-location/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a new resident location to the database
      parameters:
      - description: Resident Location ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.DeleteResidentLocationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a resident location
      tags:
      - resident_location
    put:
      consumes:
      - application/json
      description: Update a new resident location to the database
      parameters:
      - description: Resident Location ID
        in: path
        name: id
        required: true
        type: integer
      - description: Resident Location data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateResidentLocationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ResidentLocationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a resident location
      tags:
      - resident_location
  /resident-location/count:
    get:
      description: Returns count resident location from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CountResponse'
      summary: Count all resident location
      tags:
      - resident_location
swagger: "2.0"
