upstream react_wrapper {
    server react-wrapper:80;
}

upstream react_launcher {
    server react-launcher:80;
}

upstream react_settings {
    server react-settings:80;
}

upstream react_resident {
    server react-resident:80;
}

upstream go_api {
    server go-api:8080;
}

upstream nest_graphql {
    server nest-graphql:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://react_wrapper;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /launcher/ {
        proxy_pass http://react_launcher/;
        proxy_set_header Host $host;
    }

    location /external-settings/ {
        proxy_pass http://react_settings/;
        proxy_set_header Host $host;
    }

    location /external-resident/ {
        proxy_pass http://react_resident/;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://go_api;
        proxy_set_header Host $host;
    }

    location /graphql {
        proxy_pass http://nest_graphql;
        proxy_set_header Host $host;
    }
}
