upstream angular_shell {
    server angular-shell:4000;
}

upstream go_api {
    server go-api:8080;
}

upstream nest_graphql {
    server nest-graphql:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://angular_shell;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://go_api;
        proxy_set_header Host $host;
    }

    location /graphql {
        proxy_pass http://nest_graphql;
        proxy_set_header Host $host;
    }
}
